spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/daeseong?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.church.daeseong.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

app:
  upload-dir: ${user.dir}/src/main/resources/static/uploads
  admin:
    username: admin
    password: daeseong2013

logging:
  level:
    com.daeseong: DEBUG
